# <!-- Powered by BMAD™ Core -->
name: bmad-3d-unity-game-dev
version: 1.0.0
short-title: Unity C# 3D Game Dev Pack
description: 3D Game Development expansion pack for BMad Method - Unity & C# focused
author: pbean (PinkyD)
slashPrefix: bmad3du
